### ISSUE TITLE
0.10 seems to be broken

### ISSUE THREAD

**Issue by davidparsson** [sonyschan/cucumberjs-junitxml#1]
Running `cat rest_results.json | ./node_modules/cucumberjs-junitxml/bin/cucumber-junit` gives me the following stack trace:

    /path/to/node_modules/cucumberjs-junitxml/lib/cucumber_junit.js:130
        return xml({ testsuites: output }, { indent: options.indent });
                                                            ^
    TypeError: Cannot read property 'indent' of undefined
        at cucumberJunit (/path/to/node_modules/cucumberjs-junitxml/lib/cucumber_junit.js:130:57)
        at Socket.<anonymous> (/path/to/node_modules/cucumberjs-junitxml/bin/cucumber-junit:15:26)
        at Socket.emit (events.js:117:20)
        at _stream_readable.js:944:16
        at process._tickCallback (node.js:448:13)

As far as I can tell, there is no way to pass options to the command.

**Comment by sonyschan** [comment]
Thanks for pointing this out. Just patched default value of options.indent if not given.

**Comment by davidparsson** [comment]
Thanks, that's better. I realized I don't have a JSON file in the compatible format so I'm not able to verify that it works, but at least the stack trace is gone.
