### ISSUE TITLE
Difference from cucumber-junit?

### ISSUE THREAD

**Issue by davidparsson** [sonyschan/cucumberjs-junitxml#2]
What is the difference between this module and [cucumber-junit](https://github.com/stjohnjohnson/cucumber-junit)?

**Comment by sonyschan** [comment]
In my use case, the output result of cucumber.js couldn't be consumed by [cucumber-junit](https://github.com/stjohnjohnson/cucumber-junit). So I worked around by adding a custom reporter listening to test runner, which generates a workable result.json.

**Comment by davidparsson** [comment]
Is this that reporter? Or does this consume the output of that reporter?

**Comment by sonyschan** [comment]
The reporter is [Here](https://github.com/sonyschan/cucumberjs-junitxml/blob/master/reporter/reporter.js). It hooks on cucumber.js and generates result in xml format.

**Comment by davidparsson** [comment]
I thought that wasn't in the docs, but it seems it is. Nice! Thanks for your help!
