### ISSUE TITLE
Report issues on protractor-cucumber-junit?

### ISSUE THREAD

**Issue by davidparsson** [sonyschan/cucumberjs-junitxml#3]
Hi,

Where can I report issues on [protractor-cucumber-junit](https://www.npmjs.com/package/protractor-cucumber-junit)?

Sorry to use this issue tracker to ask this question which is obviously unrelated to this project, but I found no other way to get in touch.

**Comment by sonyschan** [comment]
Sorry for missing the issue. If you still have problems please raise it again. ;)

**Comment by davidparsson** [comment]
No worries, I ended up creating [cucumber-junit-reporter](https://www.npmjs.com/package/cucumber-junit-reporter) instead.
