### ISSUE TITLE
Reporter fails if reportDir does not exist

### ISSUE THREAD

**Issue by davidparsson** [sonyschan/cucumberjs-junitxml#4]
Configuring a `reportDir` in `reporter.js` that does not exist gives the following error:

    Error: ENOENT, no such file or directory '/Path/to/build/test_results/e2e/results.xml'
      at Object.fs.openSync (fs.js:439:18)
      at /Path/to/test/e2e/features/support/cucumberjs-junitxml-reporter.js:105:23
      // ....

I was thinking of creating a PR since this seemed like an easy fix, utilizing [`mkdirp.sync(reportDir)`](https://www.npmjs.com/package/mkdirp#mkdirp-sync-dir-opts) to create the report directory.

But then it hit me that this would require every user of this package to manually install `mkdirp` along side with this one, and that's not good.

A solution to this would be if `reporter.js` was kept in the `cucumberjs-junitxml` package, and required from a file in the `support` directory, instead of being copied to the `support` directory as is recommended today. That's a design that appeals to me since it also reduces duplication.

Then the only thing needed to get up and running in that case would be to create a file in the `support` directory that would look something like this:

    module.exports = require('cucumberjs-junitxml').reporter({
      reportFilePath: 'my/custom/path.xml'
    });

What do you think?

**Comment by sonyschan** [comment]
Good point. It's nice to have the report path configurable and reduce file duplication.
Did you make such change in you devbox? Feel free to send a PR if you've done. :)

**Comment by davidparsson** [comment]
I wanted to let you know that, since I had other issues with this plugin and since I'm in need of a JUnit reporter for another testing framework, I ended up re-writing my own reporter instead of patching this one.

If you're interested, I'll let you know when it's published.

**Comment by davidparsson** [comment]
I've published it here: https://github.com/davidparsson/cucumber-junit-reporter

**Comment by sonyschan** [comment]
@davidparsson Just back from my vacation and sorry for the late response. Thanks for the information  and glad to hear you find ways to make it. :+1:
