### ISSUE TITLE
How do you run the tests?

### ISSUE THREAD

**Issue by kmckee** [sonyschan/cucumberjs-junitxml#5]
I'm running into an issue that I think might be related to special characters in my feature files.  I was hoping to add a unit test that proves out the bug, then open up an issue and send a PR for it.

Right now I'm running: 

``` bash
yuitest tests/cucumber_junit.test.js
```

and the output is:

```
YUITest@0.7.9

Total tests: 0, Failures: 0, Skipped: 0, Time: 0.004 seconds
```

I've never used this test runner and I'm probably just missing something obvious. 

Thanks for your help!

**Comment by sonyschan** [comment]
Sorry for missing the issue. Hope you resolved the problem. If you have further question please raise it again. ;)
